kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: |
    <settings
      xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

      <localRepository>${user.home}/.m2/repository</localRepository>

      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>Home Nexus</name>
          <url>http://192.168.1.95:8081/repository/maven-redhat/</url>
          <mirrorOf>central</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
